// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFn7Bklz0SPaXg1hbDqikg5JPpgSGA30',
    appId: '1:1005805604140:web:92604856c12018008ef089',
    messagingSenderId: '1005805604140',
    projectId: 'flutter-shop-test-project',
    authDomain: 'flutter-shop-test-project.firebaseapp.com',
    storageBucket: 'flutter-shop-test-project.firebasestorage.app',
    measurementId: 'G-Y0Y2D3NJL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcXUFbJJ7q8LzMOdv3hLSHClRx6vJ5lxI',
    appId: '1:1005805604140:android:c26fd7847f6a393d8ef089',
    messagingSenderId: '1005805604140',
    projectId: 'flutter-shop-test-project',
    storageBucket: 'flutter-shop-test-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdv1rbiPtpHD-gkNd_mKF_EOzVSEij0hs',
    appId: '1:1005805604140:ios:f92e26de3550a9058ef089',
    messagingSenderId: '1005805604140',
    projectId: 'flutter-shop-test-project',
    storageBucket: 'flutter-shop-test-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdv1rbiPtpHD-gkNd_mKF_EOzVSEij0hs',
    appId: '1:1005805604140:ios:f92e26de3550a9058ef089',
    messagingSenderId: '1005805604140',
    projectId: 'flutter-shop-test-project',
    storageBucket: 'flutter-shop-test-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsFn7Bklz0SPaXg1hbDqikg5JPpgSGA30',
    appId: '1:1005805604140:web:30a2c575c61327018ef089',
    messagingSenderId: '1005805604140',
    projectId: 'flutter-shop-test-project',
    authDomain: 'flutter-shop-test-project.firebaseapp.com',
    storageBucket: 'flutter-shop-test-project.firebasestorage.app',
    measurementId: 'G-E0ZN33SS9T',
  );
}
